language: go

go:
  - 1.8.x


before_install:
  - mysql -e 'CREATE DATABASE grid;'
install: make get-deps prepare
script:
  - make test
  - make concurrency-test
services:
  - mysql

env:
  - TEST_MYSQL_CONNECTION="root:@(127.0.0.1:3306)/%dbname%?tx_isolation=SERIALIZABLE&parseTime=true"